### ISSUE TITLE
Feature Request: Use ~/.aws/config for Default Region

### ISSUE THREAD

**Issue by eytanhanig** [whitfin/s3-meta#1]
The AWS CLI [uses the file `~/.aws/config` to set the default region](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#config-file-format) and, if included, also the `aws_access_key_id` and `aws_secret_access_key`, allowing all variables to be set in a single file.

Please add support for referencing this file to determine the default region and other variables.

**Comment by whitfin** [comment]
@eytanhanig I think if you set `AWS_PROFILE`, it might load from that file?

**Comment by matthewkmayer** [comment]
I believe https://github.com/rusoto/rusoto/issues/957 is the issue for setting the default region in Rusoto. 

Setting the `AWS_DEFAULT_REGION` environment variable should work in the meantime.

**Comment by whitfin** [comment]
@matthewkmayer yes, it looks like this is something Rusoto should support rather than patching it here. 

This currently works (i.e. loading credentials works already):

```shell
AWS_DEFAULT_REGION=us-west-2 s3-meta <bucket>
```

I'm going to close this as we follow Rusoto. For further information on what you can do now, check out their notes on auth: https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md.
